import { BlogPost } from "./types";

export const blogPosts: BlogPost[] = [
  {
    slug: "best-iphones-kenya-2024",
    title: "Best iPhones to Buy in Kenya in 2024",
    excerpt: "From budget-friendly refurbished options to the latest flagship models — we break down the best iPhone choices for every budget in Kenya.",
    content: "",
    date: "2024-11-15",
    readTime: 6,
    category: "Buying Guide",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80",
  },
  {
    slug: "new-vs-refurbished-iphone-kenya",
    title: "New vs Refurbished iPhones: Which is Better for Kenyans?",
    excerpt: "Should you buy a brand new iPhone or save with a certified refurbished device? We weigh the pros and cons so you can make the right choice.",
    content: "",
    date: "2024-11-08",
    readTime: 7,
    category: "Comparison",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
  },
  {
    slug: "iphone-battery-care-tips",
    title: "iPhone Battery Care Tips: Make Your Battery Last Longer",
    excerpt: "Learn how to maximise your iPhone battery lifespan with these proven tips from Apple-certified technicians.",
    content: "",
    date: "2024-10-22",
    readTime: 5,
    category: "Tips & Tricks",
    image: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&q=80",
  },
  {
    slug: "how-to-identify-genuine-apple-products",
    title: "How to Identify Genuine Apple Products in Kenya",
    excerpt: "Protect yourself from counterfeit Apple products. Here's your complete guide to spotting the real deal.",
    content: "",
    date: "2024-10-10",
    readTime: 8,
    category: "Consumer Tips",
    image: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80",
  },
  {
    slug: "iphone-15-features-explained",
    title: "iPhone 15 Features Explained: Is It Worth the Upgrade?",
    excerpt: "Dynamic Island, USB-C, and a 48MP camera — we explain every iPhone 15 feature and whether it's worth upgrading from your current iPhone.",
    content: "",
    date: "2024-09-28",
    readTime: 9,
    category: "Reviews",
    image: "https://images.unsplash.com/photo-1695048132520-aa5757ee47e5?w=800&q=80",
  },
  {
    slug: "smartphone-buying-guide-kenya",
    title: "Ultimate Smartphone Buying Guide for Kenya 2024",
    excerpt: "Everything you need to know before buying a smartphone in Kenya — from M-Pesa integration to the best deals on iPhones.",
    content: "",
    date: "2024-09-15",
    readTime: 10,
    category: "Buying Guide",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
  },
];
