import { Product } from "./types";

const IMG = "/images/products";

export const products: Product[] = [

  // ── iPhone 16 Pro Max ──────────────────────────────────────────────────────
  {
    id: "iph16pm-256-nt-r",
    slug: "refurbished-iphone-16-pro-max-256gb",
    name: "iPhone 16 Pro Max (Refurbished)",
    model: "iPhone 16 Pro Max",
    series: "iPhone 16",
    condition: "refurbished",
    price: 175000,
    originalPrice: 219000,
    discount: 20,
    images: [
      { url: `${IMG}/iphone-16-pro-max-natural.png`, alt: "iPhone 16 Pro Max Natural Titanium" },
      { url: `${IMG}/iphone-16-pro-max-desert.png`,  alt: "iPhone 16 Pro Max Desert Titanium" },
      { url: `${IMG}/iphone-16-pro-max-black.png`,   alt: "iPhone 16 Pro Max Black Titanium" },
    ],
    colors: [
      { name: "Natural Titanium", hex: "#C8BAA6" },
      { name: "Desert Titanium",  hex: "#C4A882" },
      { name: "Black Titanium",   hex: "#2C2C2E" },
      { name: "White Titanium",   hex: "#F5F5F0" },
    ],
    storage: ["256GB", "512GB", "1TB"],
    specs: {
      display: '6.9" Super Retina XDR, ProMotion 120Hz',
      chip: "A18 Pro",
      camera: "48MP Main + 48MP Ultra Wide + 12MP Telephoto 5x",
      battery: "Up to 33 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 95,
    warranty: "6 Months Warranty",
    rating: 4.9,
    reviews: 48,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 16 Pro Max with 95%+ battery health. Apple Intelligence, Camera Control, titanium design, and 5x Telephoto — peak iPhone at a serious saving.",
    tags: ["iphone-16", "pro-max", "refurbished", "grade-a", "5g", "dynamic-island", "magsafe", "usb-c", "flagship"],
  },

  // ── iPhone 15 Pro Max ─────────────────────────────────────────────────────
  {
    id: "iph15pm-256-bt-r",
    slug: "refurbished-iphone-15-pro-max-256gb",
    name: "iPhone 15 Pro Max (Refurbished)",
    model: "iPhone 15 Pro Max",
    series: "iPhone 15",
    condition: "refurbished",
    price: 155000,
    originalPrice: 195000,
    discount: 21,
    images: [
      { url: `${IMG}/iphone-15-pro-max-blue.png`, alt: "iPhone 15 Pro Max Blue Titanium" },
    ],
    colors: [
      { name: "Blue Titanium",    hex: "#4E6B8A" },
      { name: "Natural Titanium", hex: "#C8BAA6" },
      { name: "Black Titanium",   hex: "#2C2C2E" },
      { name: "White Titanium",   hex: "#F5F5F0" },
    ],
    storage: ["256GB", "512GB", "1TB"],
    specs: {
      display: '6.7" Super Retina XDR, ProMotion 120Hz',
      chip: "A17 Pro",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto 5x",
      battery: "Up to 29 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 93,
    warranty: "6 Months Warranty",
    rating: 4.9,
    reviews: 76,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 15 Pro Max. First titanium iPhone with A17 Pro, 5x Telephoto, and USB 3 speeds via USB-C. Incredible value.",
    tags: ["iphone-15", "pro-max", "refurbished", "grade-a", "5g", "dynamic-island", "magsafe", "usb-c", "titanium"],
  },

  // ── iPhone 15 Pro ─────────────────────────────────────────────────────────
  {
    id: "iph15p-128-nt-r",
    slug: "refurbished-iphone-15-pro-128gb",
    name: "iPhone 15 Pro (Refurbished)",
    model: "iPhone 15 Pro",
    series: "iPhone 15",
    condition: "refurbished",
    price: 130000,
    originalPrice: 165000,
    discount: 21,
    images: [
      { url: `${IMG}/iphone-15-pro-natural.png`, alt: "iPhone 15 Pro Natural Titanium" },
    ],
    colors: [
      { name: "Natural Titanium", hex: "#C8BAA6" },
      { name: "Blue Titanium",    hex: "#4E6B8A" },
      { name: "Black Titanium",   hex: "#2C2C2E" },
      { name: "White Titanium",   hex: "#F5F5F0" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    specs: {
      display: '6.1" Super Retina XDR, ProMotion 120Hz',
      chip: "A17 Pro",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto 3x",
      battery: "Up to 23 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 94,
    warranty: "6 Months Warranty",
    rating: 4.8,
    reviews: 54,
    inStock: true,
    featured: true,
    bestSeller: false,
    category: "iphone",
    description: "Grade A refurbished iPhone 15 Pro. Titanium frame, Action Button, A17 Pro chip, and USB-C with USB 3 speeds. Compact Pro power.",
    tags: ["iphone-15", "pro", "refurbished", "grade-a", "5g", "dynamic-island", "magsafe", "usb-c", "titanium"],
  },

  // ── iPhone 15 ────────────────────────────────────────────────────────────
  {
    id: "iph15-128-blk-r",
    slug: "refurbished-iphone-15-128gb",
    name: "iPhone 15 (Refurbished)",
    model: "iPhone 15",
    series: "iPhone 15",
    condition: "refurbished",
    price: 102000,
    originalPrice: 130000,
    discount: 22,
    images: [
      { url: `${IMG}/iphone-15-black.png`, alt: "iPhone 15 Black" },
    ],
    colors: [
      { name: "Black",  hex: "#1C1C1E" },
      { name: "Blue",   hex: "#A6C4E0" },
      { name: "Green",  hex: "#A5C4A6" },
      { name: "Yellow", hex: "#F5E5A0" },
      { name: "Pink",   hex: "#F2C4C0" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    specs: {
      display: '6.1" Super Retina XDR, 60Hz',
      chip: "A16 Bionic",
      camera: "48MP Main + 12MP Ultra Wide",
      battery: "Up to 20 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 93,
    warranty: "6 Months Warranty",
    rating: 4.8,
    reviews: 82,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 15. Dynamic Island, 48MP camera, USB-C, and A16 Bionic. A massive step up from any older iPhone.",
    tags: ["iphone-15", "refurbished", "grade-a", "5g", "dynamic-island", "magsafe", "usb-c"],
  },

  // ── iPhone 14 Pro Max ─────────────────────────────────────────────────────
  {
    id: "iph14pm-256-gld-r",
    slug: "refurbished-iphone-14-pro-max-256gb",
    name: "iPhone 14 Pro Max (Refurbished)",
    model: "iPhone 14 Pro Max",
    series: "iPhone 14",
    condition: "refurbished",
    price: 118000,
    originalPrice: 148000,
    discount: 20,
    images: [
      { url: `${IMG}/iphone-14-pro-max-gold.png`, alt: "iPhone 14 Pro Max Gold" },
    ],
    colors: [
      { name: "Gold",        hex: "#F4E4C5" },
      { name: "Space Black", hex: "#1C1C1E" },
      { name: "Silver",      hex: "#F5F5F7" },
      { name: "Deep Purple", hex: "#4A3B5E" },
    ],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    specs: {
      display: '6.7" Super Retina XDR, ProMotion 120Hz, Always-On',
      chip: "A16 Bionic",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto 3x",
      battery: "Up to 29 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 91,
    warranty: "6 Months Warranty",
    rating: 4.9,
    reviews: 143,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 14 Pro Max. Dynamic Island, always-on display, Emergency SOS satellite, and 48MP camera — Pro Max power at a fraction of retail.",
    tags: ["iphone-14", "pro-max", "refurbished", "grade-a", "5g", "dynamic-island", "magsafe"],
  },

  // ── iPhone 14 Pro ─────────────────────────────────────────────────────────
  {
    id: "iph14p-128-sb-r",
    slug: "refurbished-iphone-14-pro-128gb",
    name: "iPhone 14 Pro (Refurbished)",
    model: "iPhone 14 Pro",
    series: "iPhone 14",
    condition: "refurbished",
    price: 95000,
    originalPrice: 120000,
    discount: 21,
    images: [
      { url: `${IMG}/iphone-14-pro-spaceblack.png`, alt: "iPhone 14 Pro Space Black" },
    ],
    colors: [
      { name: "Space Black", hex: "#1C1C1E" },
      { name: "Silver",      hex: "#F5F5F7" },
      { name: "Gold",        hex: "#F4E4C5" },
      { name: "Deep Purple", hex: "#4A3B5E" },
    ],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    specs: {
      display: '6.1" Super Retina XDR, ProMotion 120Hz, Always-On',
      chip: "A16 Bionic",
      camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto 3x",
      battery: "Up to 23 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 90,
    warranty: "6 Months Warranty",
    rating: 4.8,
    reviews: 112,
    inStock: true,
    featured: false,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 14 Pro. Dynamic Island, always-on display, ProRes 4K video, and 48MP main camera. Compact Pro performance.",
    tags: ["iphone-14", "pro", "refurbished", "grade-a", "5g", "dynamic-island", "magsafe"],
  },

  // ── iPhone 14 ────────────────────────────────────────────────────────────
  {
    id: "iph14-128-red-r",
    slug: "refurbished-iphone-14-128gb",
    name: "iPhone 14 (Refurbished)",
    model: "iPhone 14",
    series: "iPhone 14",
    condition: "refurbished",
    price: 75000,
    originalPrice: 96000,
    discount: 22,
    images: [
      { url: `${IMG}/iphone-14-red.png`, alt: "iPhone 14 Product Red" },
    ],
    colors: [
      { name: "Red",       hex: "#BF2D2D" },
      { name: "Midnight",  hex: "#1C1C1E" },
      { name: "Starlight", hex: "#FAF7F2" },
      { name: "Blue",      hex: "#A2B8D0" },
      { name: "Purple",    hex: "#B5A9C6" },
      { name: "Yellow",    hex: "#F8E88E" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    specs: {
      display: '6.1" Super Retina XDR, 60Hz',
      chip: "A15 Bionic",
      camera: "12MP Main + 12MP Ultra Wide",
      battery: "Up to 20 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 90,
    warranty: "6 Months Warranty",
    rating: 4.7,
    reviews: 198,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 14. Emergency SOS via satellite, Crash Detection, powerful dual-camera, and 5G. A serious phone at a smart price.",
    tags: ["iphone-14", "refurbished", "grade-a", "5g", "magsafe"],
  },

  // ── iPhone 13 Pro Max ─────────────────────────────────────────────────────
  {
    id: "iph13pm-256-gld-r",
    slug: "refurbished-iphone-13-pro-max-256gb",
    name: "iPhone 13 Pro Max (Refurbished)",
    model: "iPhone 13 Pro Max",
    series: "iPhone 13",
    condition: "refurbished",
    price: 78000,
    originalPrice: 98000,
    discount: 20,
    images: [
      { url: `${IMG}/iphone-13-pro-max-gold.png`, alt: "iPhone 13 Pro Max Gold" },
    ],
    colors: [
      { name: "Gold",         hex: "#F4E4C5" },
      { name: "Sierra Blue",  hex: "#72A8C4" },
      { name: "Graphite",     hex: "#54524F" },
      { name: "Alpine Green", hex: "#4D6B52" },
      { name: "Silver",       hex: "#F5F5F7" },
    ],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    specs: {
      display: '6.7" Super Retina XDR, ProMotion 120Hz',
      chip: "A15 Bionic",
      camera: "12MP Main + 12MP Ultra Wide + 12MP Telephoto 3x",
      battery: "Up to 28 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 91,
    warranty: "6 Months Warranty",
    rating: 4.8,
    reviews: 234,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 13 Pro Max. ProMotion 120Hz, ProRes video, macro camera, and the longest battery of any iPhone 13 — at 30% off retail.",
    tags: ["iphone-13", "pro-max", "refurbished", "grade-a", "5g", "magsafe"],
  },

  // ── iPhone 13 Pro ─────────────────────────────────────────────────────────
  {
    id: "iph13p-128-sil-r",
    slug: "refurbished-iphone-13-pro-128gb",
    name: "iPhone 13 Pro (Refurbished)",
    model: "iPhone 13 Pro",
    series: "iPhone 13",
    condition: "refurbished",
    price: 68000,
    originalPrice: 88000,
    discount: 23,
    images: [
      { url: `${IMG}/iphone-13-pro-silver.png`, alt: "iPhone 13 Pro Silver" },
    ],
    colors: [
      { name: "Silver",       hex: "#F5F5F7" },
      { name: "Sierra Blue",  hex: "#72A8C4" },
      { name: "Graphite",     hex: "#54524F" },
      { name: "Gold",         hex: "#F4E4C5" },
      { name: "Alpine Green", hex: "#4D6B52" },
    ],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    specs: {
      display: '6.1" Super Retina XDR, ProMotion 120Hz',
      chip: "A15 Bionic",
      camera: "12MP Main + 12MP Ultra Wide + 12MP Telephoto 3x",
      battery: "Up to 23 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 92,
    warranty: "6 Months Warranty",
    rating: 4.8,
    reviews: 187,
    inStock: true,
    featured: false,
    bestSeller: false,
    category: "iphone",
    description: "Grade A refurbished iPhone 13 Pro. ProMotion 120Hz, macro photography, ProRes 4K video, and 5G — all at a compelling Kenyan price.",
    tags: ["iphone-13", "pro", "refurbished", "grade-a", "5g", "magsafe"],
  },

  // ── iPhone 13 ────────────────────────────────────────────────────────────
  {
    id: "iph13-128-red-r",
    slug: "refurbished-iphone-13-128gb",
    name: "iPhone 13 (Refurbished)",
    model: "iPhone 13",
    series: "iPhone 13",
    condition: "refurbished",
    price: 55000,
    originalPrice: 70000,
    discount: 21,
    images: [
      { url: `${IMG}/iphone-13-red.jpg`, alt: "iPhone 13 Product Red" },
    ],
    colors: [
      { name: "Red",       hex: "#BF2D2D" },
      { name: "Midnight",  hex: "#1C1C1E" },
      { name: "Starlight", hex: "#FAF7F2" },
      { name: "Blue",      hex: "#4A7DAD" },
      { name: "Pink",      hex: "#F4B8C1" },
      { name: "Green",     hex: "#5E8F6D" },
    ],
    storage: ["128GB", "256GB"],
    specs: {
      display: '6.1" Super Retina XDR, 60Hz',
      chip: "A15 Bionic",
      camera: "12MP Main + 12MP Ultra Wide",
      battery: "Up to 19 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 92,
    warranty: "6 Months Warranty",
    rating: 4.7,
    reviews: 412,
    inStock: true,
    featured: true,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 13. A15 Bionic, improved dual cameras, all-day battery, 5G, and MagSafe. Our most popular refurbished model in Kenya.",
    tags: ["iphone-13", "refurbished", "grade-a", "5g", "magsafe", "best-value"],
  },

  // ── iPhone 12 Pro Max ─────────────────────────────────────────────────────
  {
    id: "iph12pm-128-gld-r",
    slug: "refurbished-iphone-12-pro-max-128gb",
    name: "iPhone 12 Pro Max (Refurbished)",
    model: "iPhone 12 Pro Max",
    series: "iPhone 12",
    condition: "refurbished",
    price: 50000,
    originalPrice: 65000,
    discount: 23,
    images: [
      { url: `${IMG}/iphone-12-pro-max-gold.png`, alt: "iPhone 12 Pro Max Gold" },
    ],
    colors: [
      { name: "Gold",         hex: "#F4E4C5" },
      { name: "Pacific Blue", hex: "#2C5F7A" },
      { name: "Graphite",     hex: "#54524F" },
      { name: "Silver",       hex: "#F5F5F7" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    specs: {
      display: '6.7" Super Retina XDR, 60Hz',
      chip: "A14 Bionic",
      camera: "12MP Main + 12MP Ultra Wide + 12MP Telephoto 2.5x",
      battery: "Up to 20 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 89,
    warranty: "6 Months Warranty",
    rating: 4.7,
    reviews: 289,
    inStock: true,
    featured: false,
    bestSeller: true,
    category: "iphone",
    description: "Grade A refurbished iPhone 12 Pro Max. The largest ever iPhone screen at the time, LiDAR scanner, MagSafe, and 5G at a great Kenyan price.",
    tags: ["iphone-12", "pro-max", "refurbished", "grade-a", "5g", "magsafe"],
  },

  // ── iPhone 12 Pro ─────────────────────────────────────────────────────────
  {
    id: "iph12p-128-pb-r",
    slug: "refurbished-iphone-12-pro-128gb",
    name: "iPhone 12 Pro (Refurbished)",
    model: "iPhone 12 Pro",
    series: "iPhone 12",
    condition: "refurbished",
    price: 44000,
    originalPrice: 58000,
    discount: 24,
    images: [
      { url: `${IMG}/iphone-12-pro-pacific-blue.png`, alt: "iPhone 12 Pro Pacific Blue" },
    ],
    colors: [
      { name: "Pacific Blue", hex: "#2C5F7A" },
      { name: "Gold",         hex: "#F4E4C5" },
      { name: "Graphite",     hex: "#54524F" },
      { name: "Silver",       hex: "#F5F5F7" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    specs: {
      display: '6.1" Super Retina XDR, 60Hz',
      chip: "A14 Bionic",
      camera: "12MP Main + 12MP Ultra Wide + 12MP Telephoto 2x",
      battery: "Up to 17 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 88,
    warranty: "6 Months Warranty",
    rating: 4.6,
    reviews: 321,
    inStock: true,
    featured: false,
    bestSeller: false,
    category: "iphone",
    description: "Grade A refurbished iPhone 12 Pro. Stainless steel frame, LiDAR scanner, MagSafe wireless charging, and 5G. Pro photography at a budget price.",
    tags: ["iphone-12", "pro", "refurbished", "grade-a", "5g", "magsafe"],
  },

  // ── iPhone 12 mini ────────────────────────────────────────────────────────
  {
    id: "iph12mini-64-red-r",
    slug: "refurbished-iphone-12-mini-64gb",
    name: "iPhone 12 mini (Refurbished)",
    model: "iPhone 12 mini",
    series: "iPhone 12",
    condition: "refurbished",
    price: 30000,
    originalPrice: 40000,
    discount: 25,
    images: [
      { url: `${IMG}/iphone-12-mini-red.jpg`, alt: "iPhone 12 mini Product Red" },
    ],
    colors: [
      { name: "Red",    hex: "#BF2D2D" },
      { name: "Black",  hex: "#1C1C1E" },
      { name: "White",  hex: "#F5F5F7" },
      { name: "Blue",   hex: "#003F5E" },
      { name: "Green",  hex: "#4A7A5D" },
      { name: "Purple", hex: "#5C5B8E" },
    ],
    storage: ["64GB", "128GB", "256GB"],
    specs: {
      display: '5.4" Super Retina XDR, 60Hz',
      chip: "A14 Bionic",
      camera: "12MP Main + 12MP Ultra Wide",
      battery: "Up to 15 hours video playback",
      os: "iOS 18",
      network: "5G",
    },
    batteryHealth: 87,
    warranty: "6 Months Warranty",
    rating: 4.6,
    reviews: 267,
    inStock: true,
    featured: false,
    bestSeller: false,
    category: "iphone",
    description: "Grade A refurbished iPhone 12 mini. The smallest, lightest 5G iPhone ever made. Perfect one-handed device with full MagSafe support.",
    tags: ["iphone-12", "mini", "refurbished", "grade-a", "5g", "magsafe", "compact"],
  },

  // ── iPhone 11 Pro Max ─────────────────────────────────────────────────────
  {
    id: "iph11pm-64-sil-r",
    slug: "refurbished-iphone-11-pro-max-64gb",
    name: "iPhone 11 Pro Max (Refurbished)",
    model: "iPhone 11 Pro Max",
    series: "iPhone 11",
    condition: "refurbished",
    price: 34000,
    originalPrice: 46000,
    discount: 26,
    images: [
      { url: `${IMG}/iphone-11-pro-max-silver.jpg`, alt: "iPhone 11 Pro Max Silver" },
    ],
    colors: [
      { name: "Silver",         hex: "#F5F5F7" },
      { name: "Space Gray",     hex: "#3A3A3C" },
      { name: "Gold",           hex: "#F4E4C5" },
      { name: "Midnight Green", hex: "#3A4A40" },
    ],
    storage: ["64GB", "256GB", "512GB"],
    specs: {
      display: '6.5" Super Retina XDR, 60Hz',
      chip: "A13 Bionic",
      camera: "12MP Main + 12MP Ultra Wide + 12MP Telephoto 2x",
      battery: "Up to 20 hours video playback",
      os: "iOS 17",
      network: "4G LTE",
    },
    batteryHealth: 85,
    warranty: "3 Months Warranty",
    rating: 4.6,
    reviews: 389,
    inStock: true,
    featured: false,
    bestSeller: false,
    category: "iphone",
    description: "Grade A refurbished iPhone 11 Pro Max. Triple camera with Night mode, Super Retina XDR display, and stainless steel frame at an exceptional price.",
    tags: ["iphone-11", "pro-max", "refurbished", "grade-a", "budget"],
  },

  // ── iPhone 11 ────────────────────────────────────────────────────────────
  {
    id: "iph11-64-red-r",
    slug: "refurbished-iphone-11-64gb",
    name: "iPhone 11 (Refurbished)",
    model: "iPhone 11",
    series: "iPhone 11",
    condition: "refurbished",
    price: 22000,
    originalPrice: 30000,
    discount: 27,
    images: [
      { url: `${IMG}/iphone-11-red.jpg`, alt: "iPhone 11 Product Red" },
    ],
    colors: [
      { name: "Red",    hex: "#BF2D2D" },
      { name: "Black",  hex: "#1C1C1E" },
      { name: "White",  hex: "#F5F5F7" },
      { name: "Yellow", hex: "#F5D547" },
      { name: "Green",  hex: "#4CAF6A" },
      { name: "Purple", hex: "#8E6BAD" },
    ],
    storage: ["64GB", "128GB", "256GB"],
    specs: {
      display: '6.1" Liquid Retina HD, 60Hz',
      chip: "A13 Bionic",
      camera: "12MP Main + 12MP Ultra Wide",
      battery: "Up to 17 hours video playback",
      os: "iOS 17",
      network: "4G LTE",
    },
    batteryHealth: 86,
    warranty: "3 Months Warranty",
    rating: 4.5,
    reviews: 712,
    inStock: true,
    featured: false,
    bestSeller: true,
    category: "iphone",
    description: "Certified refurbished iPhone 11. Dual-camera with Night mode, Face ID, and A13 Bionic chip — the most affordable way into the Apple ecosystem in Kenya.",
    tags: ["iphone-11", "refurbished", "grade-a", "budget", "entry-level"],
  },
];

export const getFeaturedProducts   = () => products.filter((p) => p.featured);
export const getBestSellers        = () => products.filter((p) => p.bestSeller);
export const getRefurbishedProducts= () => products.filter((p) => p.condition === "refurbished");
export const getNewProducts        = () => products.filter((p) => p.condition === "new");

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug) ?? null;

export const formatPrice = (price: number) =>
  new Intl.NumberFormat("en-KE", {
    style: "currency",
    currency: "KES",
    minimumFractionDigits: 0,
  }).format(price);

export const getRelatedProducts = (product: Product, limit = 4) => {
  const sameSeries = products.filter(
    (p) => p.id !== product.id && p.series === product.series
  ).slice(0, limit);

  const others = products.filter(
    (p) => p.id !== product.id && p.series !== product.series && p.category === product.category
  ).slice(0, Math.max(0, limit - sameSeries.length));

  return [...sameSeries, ...others];
};
